application: hanhuy-acra
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /api/.*
  script: crashreports.api.app
- url: /reports/.*
  script: crashreports.crashreports.app
  login: admin
- url: /
  script: main.main.app
  login: admin
