application: hanhuy-acra
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: crashreports.api.app
- url: /reports/.*
  script: crashreports.crashreports.app
  login: admin
- url: /
  script: main.main.app
  login: admin
