application: hanhuy-acra
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /js/(.*\.html)
  static_files: js/\1
  upload: js/(.*\.html)

- url: /js/(.*\.js)
  static_files: js/\1
  upload: js/(.*\.js)

- url: /js/(.*\.css)
  static_files: js/\1
  upload: js/(.*\.css)

- url: /js/(.*\.map)
  static_files: js/\1
  upload: js/(.*\.map)

#- url: /js/(.*\.md)
#  mime_type: text/plain
#  static_files: js/\1
#  upload: js/(.*\.md)

#- url: /js/(.*\.json)
#  mime_type: text/plain
#  static_files: js/\1
#  upload: js/(.*\.json)

- url: /public/.*
  script: crashreports.public.app

- url: /api/.*
  script: crashreports.api.app

- url: /reports/.*
  script: crashreports.crashreports.app
  login: admin

- url: /
  script: main.main.app
  login: admin
